name: Build and deploy a Spring app to App Service

on:
  push:
    branches:
    - "msi-test"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
    # Check out repo to the VM
    - uses: actions/checkout@v1
    
    # Maven build
    - name: Build and test with Maven
      run: mvn clean package

    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'freebergwindowsjavase'
        publish-profile: ${{ secrets.PUB_PROFILE_FREEBERGTOMCATTEST }}
        package: 'target/app.war' 