on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Maven build
      run: mvn clean package
    
    # Finally, deploy the app to App Service (https://github.com/Azure/webapps-deploy)
    - uses: azure/webapps-deploy@v1
      with:
        app-name: "my-cool-app"
        publish-profile: ${{ secrets.SRING_DEMO_PUBLISH_PROFILE }}
        package: /backend/target/*.jar
      
