name: Build, publish, and deploy a Dockerized Spring app to App Service

on:
  push:
    branches:
      dockerized-jar

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Maven
      run: mvn clean package
    
    
